name = "nikhils9/cip68-nfts"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'nikhils9/cip68-nfts'"

[repository]
user = "nikhils9"
project = "cip68-nfts"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.5.0"
source = "github"
